// Client-safe data module — provides defaults when store is unavailable
// Server components should import { readSiteData } from "@/lib/store" instead
import type { Cast, Course, Area } from "@/types";

export const courses: Course[] = [
    { id: "standard-60", name: { en: "Standard 60", zh: "标准 60", ja: "スタンダード 60", fr: "Standard 60", es: "Estándar 60", hi: "स्टैंडर्ड 60" }, duration: 60, price: 30000, description: { en: "Our standard 60-minute course", zh: "标准60分钟方案", ja: "スタンダードの60分コース", fr: "Notre formule standard de 60 minutes", es: "Nuestro curso estándar de 60 minutos", hi: "हमारा मानक 60 मिनट का कोर्स" } },
    { id: "standard-90", name: { en: "Standard 90", zh: "标准 90", ja: "スタンダード 90", fr: "Standard 90", es: "Estándar 90", hi: "स्टैंडर्ड 90" }, duration: 90, price: 42000, description: { en: "Extended 90-minute experience", zh: "延长90分钟体验", ja: "ロングの90分コース", fr: "Expérience prolongée de 90 minutes", es: "Experiencia extendida de 90 minutos", hi: "विस्तारित 90 मिनट का अनुभव" } },
    { id: "premium-120", name: { en: "Premium 120", zh: "尊享 120", ja: "プレミアム 120", fr: "Premium 120", es: "Premium 120", hi: "प्रीमियम 120" }, duration: 120, price: 55000, description: { en: "Premium 2-hour experience", zh: "尊享2小时体验", ja: "プレミアムの120分コース", fr: "Expérience premium de 2 heures", es: "Experiencia premium de 2 horas", hi: "प्रीमियम 2 घंटे का अनुभव" } },
    { id: "vip-180", name: { en: "VIP 180", zh: "VIP 180", ja: "VIP 180", fr: "VIP 180", es: "VIP 180", hi: "VIP 180" }, duration: 180, price: 80000, description: { en: "VIP 3-hour experience", zh: "VIP 3小时极致体验", ja: "VIPの180分コース", fr: "Expérience VIP de 3 heures", es: "Experiencia VIP de 3 horas", hi: "VIP 3 घंटे का अनुभव" } },
];

export const areas: Area[] = [
    { id: "roppongi", slug: "roppongi", name: { en: "Roppongi", ja: "六本木", zh: "六本木", fr: "Roppongi", es: "Roppongi", hi: "रोप्पोंगी" }, description: { en: "Premier entertainment district", ja: "六本木ヒルズ、東京ミッドタウン", zh: "六本木Hills", fr: "Roppongi Hills", es: "Roppongi Hills", hi: "रोप्पोंगी हिल्स" }, transportMinutes: 15, transportFee: 0 },
    { id: "akasaka", slug: "akasaka", name: { en: "Akasaka", ja: "赤坂", zh: "赤坂", fr: "Akasaka", es: "Akasaka", hi: "अकासाका" }, description: { en: "Luxury hotel district", ja: "高級ホテルエリア", zh: "高级酒店区", fr: "Quartier hôtelier", es: "Zona hotelera", hi: "लक्जरी होटल" }, transportMinutes: 20, transportFee: 0 },
    { id: "shinjuku", slug: "shinjuku", name: { en: "Shinjuku", ja: "新宿", zh: "新宿", fr: "Shinjuku", es: "Shinjuku", hi: "शिंजुकु" }, description: { en: "Business and entertainment hub", ja: "ビジネスとエンターテインメントの中心", zh: "商业娱乐中心", fr: "Centre d'affaires", es: "Centro de negocios", hi: "व्यापार केंद्र" }, transportMinutes: 25, transportFee: 2000 },
    { id: "shibuya", slug: "shibuya", name: { en: "Shibuya", ja: "渋谷", zh: "涩谷", fr: "Shibuya", es: "Shibuya", hi: "शिबुया" }, description: { en: "Iconic Tokyo district", ja: "東京の象徴的なエリア", zh: "东京标志性地区", fr: "Quartier emblématique", es: "Distrito icónico", hi: "प्रतिष्ठित जिला" }, transportMinutes: 20, transportFee: 1000 },
    { id: "ginza", slug: "ginza", name: { en: "Ginza", ja: "銀座", zh: "银座", fr: "Ginza", es: "Ginza", hi: "गिन्ज़ा" }, description: { en: "Prestigious shopping district", ja: "東京最高峰のショッピングエリア", zh: "最负盛名的购物区", fr: "Quartier commerçant", es: "Distrito comercial", hi: "प्रतिष्ठित शॉपिंग" }, transportMinutes: 25, transportFee: 2000 },
];

export const demoCasts: Cast[] = [
    { id: "cast-001", name: "Yui", age: 23, height: 162, bust: 86, cup: "D", waist: 57, hip: 85, images: ["/images/cast/placeholder.jpg"], profile: { en: "Elegant and charming", ja: "エレガントで魅力的" }, castComment: { ja: "" }, storeComment: { ja: "" }, tags: [], nationality: "Japanese", languages: ["Japanese", "English"], smoking: false, tattoo: false, isNew: false, isRecommended: true, available: true, availableFrom: "18:00", availableUntil: "02:00" },
    { id: "cast-002", name: "Hana", age: 25, height: 168, bust: 88, cup: "E", waist: 58, hip: 87, images: ["/images/cast/placeholder.jpg"], profile: { en: "Tall and stunning", ja: "長身で美しい" }, castComment: { ja: "" }, storeComment: { ja: "" }, tags: [], nationality: "Japanese", languages: ["Japanese", "English"], smoking: false, tattoo: false, isNew: true, isRecommended: false, available: true, availableFrom: "19:00", availableUntil: "03:00" },
    { id: "cast-003", name: "Mei", age: 22, height: 158, bust: 84, cup: "C", waist: 56, hip: 83, images: ["/images/cast/placeholder.jpg"], profile: { en: "Sweet and playful", ja: "甘くて茶目っ気" }, castComment: { ja: "" }, storeComment: { ja: "" }, tags: [], nationality: "Japanese", languages: ["Japanese", "English", "Chinese"], smoking: false, tattoo: false, isNew: false, isRecommended: true, available: false },
]; 